version: "3"
services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - ./local/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Dora
      - POSTGRES_PASSWORD=Dora
      - POSTGRES_DB=blog
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - ALEMBIC_CONFIG=/app/api/alembic/alembic.ini
      - PYTHONPATH=/app
    command: bash -c "cd /app/api/alembic && alembic upgrade head && cd .. && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db